### ISSUE TITLE
Deliverable

### ISSUE THREAD

**Issue by MOHOAzure** [MOHOAzure/hw-backend-api#5]
- [x] Hw codes uploaded to this GitHub repo
- [x] README.md
   - [x] Framework and dependency #1 
   - [x] API spec and URL #3
   - [x] DB design and schema #2 #4 
   - [x] Data Import #6 
   - [x] Architecture and component design #8
   - [x] Demo
- [x] Email back with hw GitHub repo URL
